### PR TITLE
Calendar development

### LINKED ISSUE #20: [MAJOR] Create Calendar Page
Create a working skeleton of the Calendar page

### PR DESCRIPTION
**Pull request by ezh247467**
Created a skeleton of the Calendar with only Add and Delete tasks.

### CODE REVIEW

**Comment by ezh247467** [comment]
This is currently only working with LocalStorage though.

**Comment by BuppiBonzai** [comment]
The css is a bit funky. Changing calendar day size based on resolution causes really funky resizing issues at smaller resolutions, and the header gets cut off at 1080p but not on 1440p (removing height from body seemed to fix that). It might be better to keep things more fixed if we want to consider how it looks on a lower res device like a phone. Otherwise this feels like a good launch point to choose our direction for further development.

**Review by schowbey — COMMENTED** [review]
Functionality looks good to me! Little bit concerned about using local storage, is that the long-term solution we will be using?

**Comment by ezh247467** [comment]
> Functionality looks good to me! Little bit concerned about using local storage, is that the long-term solution we will be using?

I was only using local storage to test the functionality of the calendar. If we are doing some sort of database, then we can change the code to work with it once we get it set up and running.

**Comment by ezh247467** [comment]
> The css is a bit funky. Changing calendar day size based on resolution causes really funky resizing issues at smaller resolutions, and the header gets cut off at 1080p but not on 1440p (removing height from body seemed to fix that). It might be better to keep things more fixed if we want to consider how it looks on a lower res device like a phone. Otherwise this feels like a good launch point to choose our direction for further development.

Yeah, I prioritized functionality over styling so any styling changes you have in mind I leave to your discretion.

**Review by schowbey — APPROVED** [review]
good to merge

**Comment by ezh247467** [comment]
Due to there being too many complex conflicts between the main branch and our branch, it was recommended to do a manual merge, which I just did. I am not yet merging to the main branch since there are new styling issues with the addition of the navbar. We will need to fix this first.

**Pull request merged**
