### PR TITLE
Quality of Life Changes for Project Tasks

### PR DESCRIPTION
**Pull request by ezh247467**
Calendar now supports color-coded labels for Project Tasks (Colors are kinda random so visibility may vary. We may need to resolve this issue later). The task form modal now separates "event tasks" and Project Tasks into different categories where each Project has a sublist of tasks that are due on that day.

### CODE REVIEW

**Review by BuppiBonzai — COMMENTED** [review]
tried it out, seems fine for now. Will look for possible bugs later

**Review by schowbey — COMMENTED** [review]
maybe we should pre-define an array of 20ish colors that are accessible, then based on the project number, assign that color.

**Comment by aryand10** [comment]
> maybe we should pre-define an array of 20ish colors that are accessible, then based on the project number, assign that color.

I think this is a good way to go, project based color separation would probably be best for user experience

**Comment by ezh247467** [comment]
> maybe we should pre-define an array of 20ish colors that are accessible, then based on the project number, assign that color.

While I certainly agree @schowbey, there may be a couple of issues that @aryand10 and @NirvekPanda would need to take into account for their Projects page. The projectsData in localStorage does not have any form of ID for the projects, which I believe is what you meant by project number. As of now, I am using the Project title to hash the colors, but those can be named into any string, not just project numbers, so I can't do anything about that as of now. The second possible issue would be having more projects than colors. What should we do in that case?

**Comment by schowbey** [comment]
@ezh247467 that is interesting (and difficult).  If there is no project ID, I'd suggest continuing to generate random colors, but restricting the range. Use RGB values since bigger values are always lighter (and lower = darker). Maybe something like below.

```
  const r = Math.floor(Math.random() * (192 - 64) + 64);
  const g = Math.floor(Math.random() * (192 - 64) + 64);
  const b = Math.floor(Math.random() * (192 - 64) + 64);
  
  return `rgb(${r}, ${g}, ${b})`;

```

**Comment by ezh247467** [comment]
I may have caused a bit of a misunderstanding. The colors are not generated by using any random functions as I do need it to be deterministic so tasks of the same project name get the same color. I called it random since I personally do not know what color will be generated. The current method is hashing the characters of the project title and converting it into a hexadecimal color. I will try tinkering with the code to guarantee a lighter color using your suggestion as inspiration.

**Review by schowbey — APPROVED** [review]
looks great, thanks for the compromise :)

**Pull request merged**
